config/routes.rb
Rails.application.routes.draw do

root 'products#index'

 resources :sessions, only: [:new, :create, :destroy]
 resources :products do
  resources :reviews, only: [:show, :create, :destroy]
end
 resources :users, only: [:new, :create, :show] do
 	resources :reviews, only: [:show, :create, :destroy]
 end
end

app/models/product.rb
class Product < ActiveRecord::Base
	attr_accessor :price_in_dollars
	validates :description, :name, presence: true
	
	# validates :price_in_cents, numericality: true

    has_many :reviews
    has_many :users, through: :reviews

    before_save :convert_price
  def convert_price
  	self.price_in_cents = self.price_in_dollars.to_f * 100
  end

  def formatted_price
	price_in_dollars = price_in_cents.to_f / 100
	sprintf("%.2f", price_in_dollars)
  end

end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :product
	belongs_to :user

	validates :comment, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :reviews
	has_many :products, through: :reviews
	validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def ensure_logged_in
  	unless current_user
  		flash[:alert] = "Please log in"
  		redirect_to new_session_path
  	end
  end

  helper_method :current_user
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index

    @products = if params[:search]
      Product.where("LOWER(name) LIKE LOWER(?)", "%#{params[:search]}%")
    else
      Product.all
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
  	@product = Product.find(params[:id])

  	if current_user
  		@review = Review.new
  	end
  end

  def new
  	@product = Product.new
  end

  def edit
  	@product = Product.find(params[:id])
  end

  def create
  	@product = Product.new(product_params)

  	if @product.save
  	  redirect_to products_path
    else
  	  render "new"
    end
  end

  def update
    @product = Product.find(params[:id])

    if @product.update_attributes(product_params)
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private
  def product_params
    params.require(:product).permit(:name, :description, :price_in_cents, :price_in_dollars, :image)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_filter :ensure_logged_in, only: [:create, :destroy]
  before_filter :load_product
  def new
  @review = Review.new
  end 

  def show
  	@review = Review.find(params[:id])
  end

  def create
  	# @review = @product.reviews.build(review_params)
   #  @review.user = current_user

      @review = Review.new(
      comment: params[:review][:comment],
      product_id: @product.id,
      user_id: current_user.id
     )    
    respond_to do |format| 
        
        if @review.save
          format.html do
              if request.xhr?
                render @review
              else
            	redirect_to product_path(@product), notice: 'Review created successfully!'
              end
          end


          format.js
        else
          format.html do
        	   render 'products/show'
          end
          format.js
      end
    end
  end


  def destroy
  	@review = Review.find(params[:id])
    @review.destroy
    redirect_to product_path(@review.product)
  end

  private 
  def review_params
  	params.require(:review).permit(:comment, :product_id)
  end

  def load_product
  	@product = Product.find(params[:product_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to products_url, :notice => "Logged in!"
    else
    	flash.now[:alert] = "Invalid email or password"
      render "new"
    end
  end

  def destroy
  	session[:user_id] = nil
    redirect_to products_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def show
    @user = current_user
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		redirect_to products_url, notice: "Signed up!"
  	else 
  		render "new"
  	end
  end

  private
  def user_params
  	params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rainforest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<header>
 <p class="userinfo">
      <% if current_user %>
        Signed in as <%= link_to current_user.name, user_path(current_user) %>. <%= link_to "Log out", session_path("current"), :method => :delete %>
      <% else %>
        <%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
      <% end %>
    </p>
<h1>Rainforest</h1>
</header>
<body>
    <% if flash[:notice] %>
      <p id="notice"><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:alert] %>
      <p id="alert"><%= flash[:alert] %></p>
    <% end %>

    <%= yield %>

  </body>
</html>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
     <% end %> 
      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= form_for(@product) do |f| %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label "Price" %><br />
    <%= f.text_field :price_in_dollars %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <div class="field">
  <%= f.label :image %><br />
  <%= f.text_field :image %>
  </div>
<% end %>

app/views/products/_product.html.erb
<table class = "tablestyle">
<tr>
<th style = "width: 200px; height: 150px;"><img src= "<%= product.image %>" style= "width: 150px; height: 150px;"></th>
<th style = "width: 200px; height: 150px; font-size: 25px;"><%=link_to "#{product.name}" , product_path(product) %></th>
<th style = "width: 200px; height: 150px;"><%= product.description %><th>
<th style = "width: 200px; height: 150px;"><%= product.formatted_price %>$</th>
</tr>
</table>

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>

app/views/products/index.html.erb
<%= form_tag products_path, method: :get, authentication: false, id: 'search-form' do %>
<%= text_field_tag :search, params[:search] %>
<%= submit_tag "Search" %>
<% end %>

<p class = "new">
<a href="/products/new">Create New Product</a></p>

<div id="products">
<%= render @products %>
</div>




<script type="text/javascript">

	// function display_search_results() {
	// 	if (this.readyState === 4) {
	// 		console.log(this);
	// 		document.getElementById('products').innerHTML = this.responseText;
	// 	}
	// }

	// var form = document.getElementById('search-form');
	// form.addEventListener('submit', function(event) {
	// 	event.preventDefault();
	// 	var searchValue = document.getElementById('search').value;

	// 	var xhr = new XMLHttpRequest();
	// 	xhr.onload =  display_search_results;
	// 	xhr.open('GET', '/products?search=' + searchValue, true);
	// 	xhr.setRequestHeader("X-Requested-With", "XMLHttpRequest");
	// 	xhr.send();
	// });

</script>

app/views/products/index.js.erb
$('#products').html("<%= j(render @products) %>");

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p class = 'showpage'>Name: <%= @product.name %><br>
Description: <%= @product.description %><br>
Price: <%= @product.formatted_price %><br>
<img src="<%= @product.image %>" class = "photo"></p>
<div class = "showpage">
<h3>Reviews</h3>

<div class="reviews-list">
 <%= render @product.reviews %>
</div>

  <% if current_user %>
  <h4>New Review</h4>

  <%= form_for([@product, @review], remote: true) do |f| %>
    <% if @review.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

        <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :comment %><br />
      <%= f.text_area :comment %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to add a review.</p> 
<% end %>
</div>
<p><%= link_to "Delete Product", @photo, method: :delete, data:
{confirm: "Are you sure you want to delete?"} %>
</p>
<p> <%= link_to "Back to Products", products_path %> </p>

app/views/reviews/_review.html.erb
<% if @review.errors.any? %>
  ('body').prepend('<h2 class = "error"> Something went wrong</h2>')
<% else %>
<!-- $('.new_review').append('<$= j render @review %>');
$('#review_comment').val(''); -->
    <p>
      <%= review.comment %>
      <br>
      <% if review.user != nil %>
        <em> by <%= review.user.name %></em>
        Added on: <%= review.created_at %>
        <% end %>
        <% if review.user == current_user %>
      <%= link_to "Delete Review", product_review_path(@product, review), method: :delete %>
      <% end %>
    </p>
  


<% end %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/create.js.erb
<% if @review.errors.any? %>
	$('body').prepend('<h2 class= "error">Something went wrong!<h2>');
<% else %>
	$('.reviews-list').append('<%= j render @review %>');
	$('#review_comment').val('');
<% end %>

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field">
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>

app/views/users/show.html.erb
<h1><%= current_user.name %></h1>
<div class = "showpage"> <h3>Reviews</h3>

<% current_user.reviews.each do |review|%>
<div class = "showpage" style = "margin-bottom: 5px;">
Product: <%= review.product.name %> <br>Comment: <%= review.comment %>  <%= review.created_at  %><br>
</div>
<% end %> </div>
<p> <%= link_to "Back to Products", products_path %> </p> 